### ISSUE TITLE
[test] pythonでクライアントのリクエストを書いてみる

### ISSUE THREAD

**Issue by s1-haya** [s1-haya/webserv#14]
- [x] pythonを実行できるようにDockefileにpythonのパッケージをインストールする

**Comment by s1-haya** [comment]
pythonだとhttp_modulesとかあって便利だけど変なリクエスト（メゾットがないなど）とか送れなそう。。やからC++で書くことにした。

クライアントのリクエストはwebservがクライアントと接続できたらで良さそう。。まず通信を確立するプログラムを作ろう。nginxの設定からにしよ
```
import http.client

nginx_host = 'localhost'
nginx_port = 8080

conn = http.client.HTTPConnection(nginx_host, nginx_port)
conn.request('GET', '/')
response = conn.getresponse()
print('Status:', response.status)
conn.close()
```

**Comment by habvi** [comment]
python だと subprocess 使うと command を直に実行できたりするので、使いたかったらモジュールではなくこっちですかね
