### ISSUE TITLE
[investigation] Git hook

### ISSUE THREAD

**Issue by s1-haya** [s1-haya/webserv#50]
### 目的
.clang-formatを適用するため

**Comment by s1-haya** [comment]
### 調査結果: 
- pre-commitを設定すればコミットする前にステージされたファイルに対して実行できる。なのでcommit messageには影響がなかった。今回は自動でclang-formatを適用するような設定にした。
- 一般的に.git hookは各開発者の環境で設定するみたい。
- git commit --no-verifyと実行するとgit hooksは適用されずにcommitできる。

> The pre-commit hook is run first, before you even type in a commit message. It’s used to inspect the snapshot that’s about to be committed, to see if you’ve forgotten something, to make sure tests run, or to examine whatever you need to inspect in the code. Exiting non-zero from this hook aborts the commit, although you can bypass it with git commit --no-verify. You can do things like check for code style (run lint or something equivalent), check for trailing whitespace (the default hook does exactly this), or check for appropriate documentation on new methods

> Each hook is an executable script that Git runs before or after certain events occur in the Git life cycle. These hooks are all stored in the hooks subdirectory of the Git directory. In most projects, that’s .git/hooks

https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

### 設定方法
1. .git/hooks/pre-commitファイルを作成して以下のように記述する
```.git/hooks/pre-commit
#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(cpp|hpp)$')

if [ -z "$FILES" ]; then
    exit 0
fi

echo "$FILES" | xargs clang-format -i

echo "$FILES" | xargs git add

GREEN='\033[0;32m'
RESET='\033[0m'
echo "${GREEN}clang-format applied to staged C++ files${RESET}"

exit 0
```
2. .git/hooks/pre-commitの実行権限を付与してあげる。
`chmod +x .git/hooks/pre-commit`

### 結果
- 適用されると緑色で`clang-format applied to staged C++ files`と出力される。
```
git commit -m "test if clang-format applied"
clang-format applied to staged C++ files
[s1-haya/50-investigation-git-hook 0f2a93c] test if clang-format applied
 1 file changed, 1 insertion(+)
```

**Comment by habvi** [comment]
各自設定するんですね！すごい詳細までありがとうございます！
